[versions]
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.0"
core-ktx = "1.17.0"
hiddenapi-refine = "4.4.0"
aproc = "1.1.0"
picocli = "4.7.7"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
hiddenapi-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "hiddenapi-refine" }
hiddenapi-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "hiddenapi-refine" }
hiddenapi-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "hiddenapi-refine" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiddenapi-refine = { id = "dev.rikka.tools.refine", version.ref = "hiddenapi-refine" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aproc = { id = "xyz.mufanc.aproc", version.ref = "aproc" }
